/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.TkslUsuarios;
import dao.tksl_UsuarioDao;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import telasPesquisa.JDlgPesquisaUsuario;
import tools.util;

/**
 *
 * @author u07883409131
 */
public class JDlgUsuarios extends javax.swing.JDialog {

    private boolean incluindo;
    MaskFormatter mascaraCPF, mascaraDataNascimento;
    util util;
    public TkslUsuarios usuarios;
    tksl_UsuarioDao usuarioDao;

    /**
     * Creates new form JDlgUsuarios
     */
    public JDlgUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        habilitar(false);
        setTitle("Cadastro de Usuários ");
        setLocationRelativeTo(null);
        usuarioDao = new tksl_UsuarioDao();
        usuarios = new TkslUsuarios();

        try {
            mascaraCPF = new MaskFormatter("###.###.###-##");
            mascaraDataNascimento = new MaskFormatter("##/##/####");
        } catch (ParseException ex) {
            Logger.getLogger(JDlgUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        tksl_jFmtCpf.setFormatterFactory(new DefaultFormatterFactory(mascaraCPF));
        tksl_jFmtDataNascimento.setFormatterFactory(new DefaultFormatterFactory(mascaraDataNascimento));
    }

    public void habilitar(boolean valor) {
        util.habilitar(valor, tksl_jTxtCodigo,
                tksl_jTxtNome,
                tksl_jTxtApelido,
                tksl_jPwfSenha,
                tksl_jFmtCpf,
                tksl_jCboNivel,
                tksl_jFmtDataNascimento,
                tksl_jCboNivel,
                tksl_jChbAtivo,
                tksl_jBtnConfirmar,
                tksl_jBtnCancelar);
        util.habilitar(!valor,
                tksl_jBtnIncluir2,
                tksl_jBtnAlterar,
                tksl_jBtnExcluir,
                tksl_jBtnPesquisar);
    }

    public void limparCampos() {
        util.limparCampos(tksl_jTxtCodigo,
                tksl_jTxtNome,
                tksl_jTxtApelido,
                tksl_jPwfSenha,
                tksl_jFmtCpf,
                tksl_jCboNivel,
                tksl_jFmtDataNascimento,
                tksl_jCboNivel,
                tksl_jChbAtivo);
    }

    public TkslUsuarios viewBean() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        int id = Integer.parseInt(tksl_jTxtCodigo.getText());

        usuarios.setTkslIdUsuarios(id);
        usuarios.setTkslNome(tksl_jTxtNome.getText());
        usuarios.setTkslApelido(tksl_jTxtApelido.getText());
        usuarios.setTkslSenha(tksl_jPwfSenha.getText());
        usuarios.setTkslCpf(tksl_jFmtCpf.getText());
        try {
            usuarios.setTkslDataNascimento(dateFormat.parse(tksl_jFmtDataNascimento.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(JDlgUsuarios.class.getName()).log(Level.SEVERE, null, ex);
        }
        usuarios.setTkslNivel((String) tksl_jCboNivel.getSelectedItem());
        if (tksl_jChbAtivo.isSelected() == true) {
            usuarios.setTkslAtivo("Sim");
        } else {
            usuarios.setTkslAtivo("Não");
        }
        return usuarios;

    }

    public void beanView(TkslUsuarios usuarios) {
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        String id = String.valueOf(usuarios.getTkslIdUsuarios());
        tksl_jTxtCodigo.setText(id);
        tksl_jTxtNome.setText(usuarios.getTkslNome());
        tksl_jTxtApelido.setText(usuarios.getTkslApelido());
        tksl_jPwfSenha.setText(usuarios.getTkslSenha());
        tksl_jFmtCpf.setText(usuarios.getTkslCpf());
        tksl_jCboNivel.setSelectedItem(usuarios.getTkslNivel());
        tksl_jChbAtivo.setSelected(usuarios.getTkslAtivo().equals("Sim"));
        tksl_jFmtDataNascimento.setText(dateFormat.format(usuarios.getTkslDataNascimento()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tksl_jTxtNome = new javax.swing.JTextField();
        tksl_jTxtApelido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tksl_jTxtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tksl_jFmtCpf = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        tksl_jFmtDataNascimento = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        tksl_jPwfSenha = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        tksl_jCboNivel = new javax.swing.JComboBox<>();
        tksl_jChbAtivo = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        tksl_jBtnPesquisar = new javax.swing.JButton();
        tksl_jBtnCancelar = new javax.swing.JButton();
        tksl_jBtnConfirmar = new javax.swing.JButton();
        tksl_jBtnExcluir = new javax.swing.JButton();
        tksl_jBtnAlterar = new javax.swing.JButton();
        tksl_jBtnIncluir2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código");

        jLabel2.setText("Apelido");

        jLabel3.setText("Nome");

        jLabel4.setText("CPF");

        jLabel5.setText("Data de Nascimento");

        jLabel6.setText("Senha");

        jLabel7.setText("Nível");

        tksl_jCboNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADMINISTRADOR", "ANONIMO", "CLIENTE" }));
        tksl_jCboNivel.setSelectedIndex(-1);

        tksl_jChbAtivo.setText("Ativo");

        tksl_jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        tksl_jBtnPesquisar.setText("Pesquisar");
        tksl_jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tksl_jBtnPesquisarActionPerformed(evt);
            }
        });

        tksl_jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        tksl_jBtnCancelar.setText("Cancelar");
        tksl_jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tksl_jBtnCancelarActionPerformed(evt);
            }
        });

        tksl_jBtnConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        tksl_jBtnConfirmar.setText("Confirmar");
        tksl_jBtnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tksl_jBtnConfirmarActionPerformed(evt);
            }
        });

        tksl_jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        tksl_jBtnExcluir.setText("Excluir");
        tksl_jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tksl_jBtnExcluirActionPerformed(evt);
            }
        });

        tksl_jBtnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        tksl_jBtnAlterar.setText("Alterar");
        tksl_jBtnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tksl_tksl_jBtnAlterarActionPerformed(evt);
            }
        });

        tksl_jBtnIncluir2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        tksl_jBtnIncluir2.setText("Incluir");
        tksl_jBtnIncluir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tksl_jBtnIncluir2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tksl_jBtnPesquisar)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(tksl_jBtnIncluir2)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(tksl_jBtnAlterar)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(tksl_jBtnExcluir)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(tksl_jBtnConfirmar)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(tksl_jBtnCancelar)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(tksl_jBtnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tksl_jBtnIncluir2)
                        .addComponent(tksl_jBtnAlterar)
                        .addComponent(tksl_jBtnExcluir)
                        .addComponent(tksl_jBtnConfirmar)
                        .addComponent(tksl_jBtnCancelar))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tksl_jTxtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                    .addComponent(tksl_jTxtApelido)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(tksl_jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(tksl_jPwfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(tksl_jFmtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tksl_jCboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tksl_jChbAtivo))
                            .addComponent(tksl_jFmtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(134, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tksl_jTxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tksl_jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tksl_jTxtApelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tksl_jFmtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tksl_jFmtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tksl_jPwfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tksl_jChbAtivo)
                    .addComponent(tksl_jCboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tksl_jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tksl_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
        usuarios = new TkslUsuarios();
        JDlgPesquisaUsuario jDlgPesquisaUsuario = new JDlgPesquisaUsuario(null, true);
        jDlgPesquisaUsuario.setTelaAnterior(this);
        jDlgPesquisaUsuario.setVisible(true);
    }//GEN-LAST:event_tksl_jBtnPesquisarActionPerformed

    private void tksl_jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tksl_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        if (util.perguntar("Deseja Cancelar")) {
            usuarios = null;
            incluindo = false;
            limparCampos();
            habilitar(false);
        } else {
            util.mensagem("Cancelado");
        }
    }//GEN-LAST:event_tksl_jBtnCancelarActionPerformed

    private void tksl_jBtnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tksl_jBtnConfirmarActionPerformed
        // TODO add your handling code here:

        usuarios = viewBean();
        if (incluindo == true) {
            usuarioDao.insert(usuarios);
        } else {
            usuarioDao.update(usuarios);
        }
        habilitar(false);
        usuarios = null;
        incluindo = false;
        limparCampos();
    }//GEN-LAST:event_tksl_jBtnConfirmarActionPerformed

    private void tksl_jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tksl_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        if (usuarios != null) {
            if (util.perguntar("Deseja excluir?")) {
                usuarios = viewBean();
                usuarioDao.delete(usuarios);
                limparCampos();
                usuarios = null;
                util.mensagem("Excluido");
            } else {

                util.mensagem("exclusão cancelada");
            }
        } else {

            util.mensagem("nenhum Usuario foi selecionado");
        }
    }//GEN-LAST:event_tksl_jBtnExcluirActionPerformed

    private void tksl_tksl_jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tksl_tksl_jBtnAlterarActionPerformed
        // TODO add your handling code here:

        if (usuarios != null) {
            habilitar(true);
            incluindo = false;
            tksl_jTxtCodigo.setEnabled(false);
        } else {
            util.mensagem("Deve pesquisar antes");
        }
    }//GEN-LAST:event_tksl_tksl_jBtnAlterarActionPerformed

    private void tksl_jBtnIncluir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tksl_jBtnIncluir2ActionPerformed
        // TODO add your handling code here:
        usuarios = new TkslUsuarios();
        incluindo = true;
        habilitar(true);
        limparCampos();
    }//GEN-LAST:event_tksl_jBtnIncluir2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgUsuarios dialog = new JDlgUsuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton tksl_jBtnAlterar;
    private javax.swing.JButton tksl_jBtnCancelar;
    private javax.swing.JButton tksl_jBtnConfirmar;
    private javax.swing.JButton tksl_jBtnExcluir;
    private javax.swing.JButton tksl_jBtnIncluir2;
    private javax.swing.JButton tksl_jBtnPesquisar;
    private javax.swing.JComboBox<String> tksl_jCboNivel;
    private javax.swing.JCheckBox tksl_jChbAtivo;
    private javax.swing.JFormattedTextField tksl_jFmtCpf;
    private javax.swing.JFormattedTextField tksl_jFmtDataNascimento;
    private javax.swing.JPasswordField tksl_jPwfSenha;
    private javax.swing.JTextField tksl_jTxtApelido;
    private javax.swing.JTextField tksl_jTxtCodigo;
    private javax.swing.JTextField tksl_jTxtNome;
    // End of variables declaration//GEN-END:variables
}
