/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author u07883409131
 */
import query.JDlgConsultaCliente;
import query.JDlgConsultaProduto;
import query.JDlgConsultaUsuario;
import query.JDlgConsultaVendasProduto;
import query.JDlgConsultaVendedor;
import telasNovas.*;

public class JFrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmPrincipal() {
        initComponents();
        setTitle("Sistema de Vendas Camisas Esportivas");
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        tksl_jMnuCadastros = new javax.swing.JMenu();
        tksl_jMnuCliente = new javax.swing.JMenuItem();
        tksl_jMnuProdutoNovo = new javax.swing.JMenuItem();
        tksl_jMnuVendedorNovo = new javax.swing.JMenuItem();
        tksl_jMnuUsuarios = new javax.swing.JMenuItem();
        tksl_jSeparator1 = new javax.swing.JPopupMenu.Separator();
        tksl_jMenuItem1 = new javax.swing.JMenuItem();
        tksl_jMnuMovimento = new javax.swing.JMenu();
        tksl_jMnuVendas = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        tksl_jMnuUsuario = new javax.swing.JMenuItem();
        tksl_jMenuCliente = new javax.swing.JMenuItem();
        tksl_jMenuProduto = new javax.swing.JMenuItem();
        tksl_jMenuVendedor = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tksl_jMnuCadastros.setMnemonic('C');
        tksl_jMnuCadastros.setText("Cadastros");
        tksl_jMnuCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tksl_jMnuCadastrosActionPerformed(evt);
            }
        });

        tksl_jMnuCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        tksl_jMnuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente_1.png"))); // NOI18N
        tksl_jMnuCliente.setText("Cliente");
        tksl_jMnuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tksl_jMnuClienteActionPerformed(evt);
            }
        });
        tksl_jMnuCadastros.add(tksl_jMnuCliente);

        tksl_jMnuProdutoNovo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        tksl_jMnuProdutoNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produto_1.png"))); // NOI18N
        tksl_jMnuProdutoNovo.setText("ProdutoNovo");
        tksl_jMnuProdutoNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tksl_tksl_jMnuProdutoNovoActionPerformed(evt);
            }
        });
        tksl_jMnuCadastros.add(tksl_jMnuProdutoNovo);

        tksl_jMnuVendedorNovo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        tksl_jMnuVendedorNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/download.png"))); // NOI18N
        tksl_jMnuVendedorNovo.setText("VendedorNovo");
        tksl_jMnuVendedorNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tksl_tksl_jMnuVendedorNovoActionPerformed(evt);
            }
        });
        tksl_jMnuCadastros.add(tksl_jMnuVendedorNovo);

        tksl_jMnuUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        tksl_jMnuUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/download (1).png"))); // NOI18N
        tksl_jMnuUsuarios.setText("Usuários");
        tksl_jMnuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tksl_jMnuUsuariosActionPerformed(evt);
            }
        });
        tksl_jMnuCadastros.add(tksl_jMnuUsuarios);
        tksl_jMnuCadastros.add(tksl_jSeparator1);

        tksl_jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        tksl_jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir_1.png"))); // NOI18N
        tksl_jMenuItem1.setText("SAIR");
        tksl_jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tksl_tksl_jMenuItem1ActionPerformed(evt);
            }
        });
        tksl_jMnuCadastros.add(tksl_jMenuItem1);

        jMenuBar1.add(tksl_jMnuCadastros);

        tksl_jMnuMovimento.setText("Movimento");

        tksl_jMnuVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK));
        tksl_jMnuVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/venda.png"))); // NOI18N
        tksl_jMnuVendas.setText("Vendas");
        tksl_jMnuVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tksl_jMnuVendasActionPerformed(evt);
            }
        });
        tksl_jMnuMovimento.add(tksl_jMnuVendas);

        jMenuBar1.add(tksl_jMnuMovimento);

        jMenu1.setText("Consultas");

        tksl_jMnuUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        tksl_jMnuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/download (1).png"))); // NOI18N
        tksl_jMnuUsuario.setText("Usuários");
        tksl_jMnuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tksl_jMnuUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(tksl_jMnuUsuario);

        tksl_jMenuCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        tksl_jMenuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente.png"))); // NOI18N
        tksl_jMenuCliente.setText("Cliente");
        tksl_jMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tksl_jMenuClienteActionPerformed(evt);
            }
        });
        jMenu1.add(tksl_jMenuCliente);

        tksl_jMenuProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        tksl_jMenuProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produto.png"))); // NOI18N
        tksl_jMenuProduto.setText("Produto");
        tksl_jMenuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tksl_jMenuProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(tksl_jMenuProduto);

        tksl_jMenuVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.ALT_MASK));
        tksl_jMenuVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/download.png"))); // NOI18N
        tksl_jMenuVendedor.setText("Vendedor");
        tksl_jMenuVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tksl_jMenuVendedorActionPerformed(evt);
            }
        });
        jMenu1.add(tksl_jMenuVendedor);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, 0));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produto_1 (2).png"))); // NOI18N
        jMenuItem1.setText("Venda Produto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1545, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tksl_jMnuCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tksl_jMnuCadastrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tksl_jMnuCadastrosActionPerformed

    private void tksl_jMnuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tksl_jMnuUsuariosActionPerformed
        // TODO add your handling code here:
        JDlgUsuarios jDlgUsuarios = new JDlgUsuarios(null, true);
        jDlgUsuarios.setVisible(true);
    }//GEN-LAST:event_tksl_jMnuUsuariosActionPerformed

    private void tksl_jMnuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tksl_jMnuClienteActionPerformed
        // TODO add your handling code here:
        JDlgCliente jDlgCliente = new JDlgCliente(null, true);
        jDlgCliente.setVisible(true);
    }//GEN-LAST:event_tksl_jMnuClienteActionPerformed

    private void tksl_tksl_jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tksl_tksl_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_tksl_tksl_jMenuItem1ActionPerformed

    private void tksl_tksl_jMnuProdutoNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tksl_tksl_jMnuProdutoNovoActionPerformed
        // TODO add your handling code here:
        JDlgProdutoNovo jDlgProdutoNovo = new JDlgProdutoNovo(null, true);
        jDlgProdutoNovo.setVisible(true);
    }//GEN-LAST:event_tksl_tksl_jMnuProdutoNovoActionPerformed

    private void tksl_tksl_jMnuVendedorNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tksl_tksl_jMnuVendedorNovoActionPerformed
        // TODO add your handling code here:
        JDlgVendedorNovo jDlgVendedorNovo = new JDlgVendedorNovo(null, true);
        jDlgVendedorNovo.setVisible(true);
    }//GEN-LAST:event_tksl_tksl_jMnuVendedorNovoActionPerformed

    private void tksl_jMnuVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tksl_jMnuVendasActionPerformed
        // TODO add your handling code here:
        JDlgVendas jDlgVendas=new JDlgVendas(null, true);
        jDlgVendas.setVisible(true);
    }//GEN-LAST:event_tksl_jMnuVendasActionPerformed

    private void tksl_jMnuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tksl_jMnuUsuarioActionPerformed
        // TODO add your handling code here:
        JDlgConsultaUsuario jDlgConsultaUsuario = new JDlgConsultaUsuario(null, true);
        jDlgConsultaUsuario.setVisible(true);
        
    }//GEN-LAST:event_tksl_jMnuUsuarioActionPerformed

    private void tksl_jMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tksl_jMenuClienteActionPerformed
        // TODO add your handling code here:
        JDlgConsultaCliente jDlgConsultaCliente=new JDlgConsultaCliente(null, true);
        jDlgConsultaCliente.setVisible(true);
    }//GEN-LAST:event_tksl_jMenuClienteActionPerformed

    private void tksl_jMenuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tksl_jMenuProdutoActionPerformed
        // TODO add your handling code here:
        JDlgConsultaProduto consultaProduto=new JDlgConsultaProduto(null, true);
        consultaProduto.setVisible(true);
    }//GEN-LAST:event_tksl_jMenuProdutoActionPerformed

    private void tksl_jMenuVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tksl_jMenuVendedorActionPerformed
        // TODO add your handling code here:
        JDlgConsultaVendedor consultaVendedor=new JDlgConsultaVendedor(null, true);
        consultaVendedor.setVisible(true);
    }//GEN-LAST:event_tksl_jMenuVendedorActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JDlgConsultaVendasProduto consultaVendasProduto=new JDlgConsultaVendasProduto(null, true);
        consultaVendasProduto.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem tksl_jMenuCliente;
    private javax.swing.JMenuItem tksl_jMenuItem1;
    private javax.swing.JMenuItem tksl_jMenuProduto;
    private javax.swing.JMenuItem tksl_jMenuVendedor;
    private javax.swing.JMenu tksl_jMnuCadastros;
    private javax.swing.JMenuItem tksl_jMnuCliente;
    private javax.swing.JMenu tksl_jMnuMovimento;
    private javax.swing.JMenuItem tksl_jMnuProdutoNovo;
    private javax.swing.JMenuItem tksl_jMnuUsuario;
    private javax.swing.JMenuItem tksl_jMnuUsuarios;
    private javax.swing.JMenuItem tksl_jMnuVendas;
    private javax.swing.JMenuItem tksl_jMnuVendedorNovo;
    private javax.swing.JPopupMenu.Separator tksl_jSeparator1;
    // End of variables declaration//GEN-END:variables
}
